version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tire_request_portal_development
    ports:
      - "5432:5432"
    networks:
      - tire-portal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/rails_app
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/tire_request_portal_development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tire-portal-network
    # Command removed to use the one defined in Dockerfile

networks:
  tire-portal-network:
    driver: bridge

volumes:
  postgres_data:
